# #
#  __  __   _____          __        __
# |  \/  | |_   _|         \ \      / /   __ _   _ __     ___   _ __    ___
# | |\/| |   | |    _____   \ \ /\ / /   / _` | | '_ \   / _ \ | '_ \  / __|
# | |  | |   | |   |_____|   \ V  V /   | (_| | | |_) | |  __/ | | | | \__ \
# |_|  |_|   |_|              \_/\_/     \__,_| | .__/   \___| |_| |_| |___/
#                                               |_|
# Make sure to check the docs if you need any help: https://docs.mtwapens.nl/
#
# #
empty-sound: weapons.gunempty
weaponCooldownPerWeapon: false
projectileProtectionReducesDamage: false
damageReductionPercentagePerLevel: 5
weapons: 'Moved to weapons.yml'
ammo: 'Moved to ammo.yml'
resourcePackURL: none
showDurability: BOTH # Can be SHOOT, SWITCH, BOTH, NONE