# OofArsenal - Weapon Plugin
# Made by OofJoa
empty-sound: weapons.gunempty
weaponCooldownPerWeapon: false
projectileProtectionReducesDamage: false
damageReductionPercentagePerLevel: 5
weapons: 'Moved to weapons.yml'
ammo: 'Moved to ammo.yml'
resourcePackURL: none