
# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
  discord-orb: tkyshm/discord-orb@0.0.8
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn package

      - run:
          name: Get artifacts
          when: on_success
          command: |
            artifacts=$(curl -X GET "https://dash.mtwapens.nl/artifactparser/test")
            echo "export ARTIFACT_RESPONSE=$artifacts" >> $BASH_ENV

      - discord-orb/notify:
          success_message: "**Build:** [${CIRCLE_BUILD_NUM}](${CIRCLE_BUILD_URL}) - **Status:** [success](${CIRCLE_BUILD_URL}) - **Artifacts:** [${ARTIFACT_RESPONSE}](https://dash.mtwapens.nl/artifactparser/${CIRCLE_BUILD_NUM})"
          failure_message: "**Build:** [${CIRCLE_BUILD_NUM}](${CIRCLE_BUILD_URL}) - **Status:** [failure](${CIRCLE_BUILD_URL})"
      
      - store_artifacts:
          path: target
